version: '3'
services:
  airflow_pyspark:
    build:
      context: .
      dockerfile: docker/airflow_pyspark/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/miniconda3/lib/python3.11/site-packages/airflow/example_dags
      - ./datasets:./app/datasets
      - ./output:./app/output
    depends_on:
      - spark-worker 
  
  spark-master:
    build:
      context: .
      dockerfile: docker/airflow_pyspark/Dockerfile
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  
  spark-worker:
    build:
      context: .
      dockerfile: docker/airflow_pyspark/Dockerfile
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data